openapi: 3.0.0
info:
  title: Query Tool API
  version: v1
  description: Query Tool API

servers:
  - url: /to-be-changed/

paths:
  /to-be-changed:
    get:
      operationId: getExample
      description: example endpoint to generate api doc
      responses:
        '200':
          description: 'example endpoint result to generate api doc'
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    entityType:
      $ref: schemas/entityType.json#/EntityType
    entityDataType:
      $ref: schemas/entityDataType.json#/EntityDataType
    stringType:
      $ref: schemas/entityDataType.json#/StringType
    rangedUUIDType:
      $ref: schemas/entityDataType.json#/RangedUUIDType
    openUUIDType:
      $ref: schemas/entityDataType.json#/OpenUUIDType
    numberType:
      $ref: schemas/entityDataType.json#/NumberType
    integerType:
      $ref: schemas/entityDataType.json#/IntegerType
    booleanType:
      $ref: schemas/entityDataType.json#/BooleanType
    dateType:
      $ref: schemas/entityDataType.json#/DateType
    enumType:
      $ref: schemas/entityDataType.json#/EnumType
    objectType:
      $ref: schemas/entityDataType.json#/ObjectType
    arrayType:
      $ref: schemas/entityDataType.json#/ArrayType
    entityTypeDefaultSort:
      $ref: schemas/entityTypeDefaultSort.json
